# Generated by Django 4.2.7 on 2024-04-18 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_facebook_alter_author_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
